# Server
server:
  port: 8080

# Spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/exchange?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      connection-timeout: 30000
      connection-init-sql: 2
      maximum-pool-size: 20
      minimum-idle: 0
      connection-test-query: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000

# Mybatis
mybatis:
  type-aliases-package: nuc.nuc.onlineeducation.exchange.model
  mapper-locations: classpath:/mappers/*.xml
  config-location: classpath:/mybatis-config.xml