# Server
server:
  port: 8080

# Spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/exchange?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      connection-timeout: 30000
      connection-init-sql: 2
      maximum-pool-size: 20
      minimum-idle: 0
      connection-test-query: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
  http:
    multipart:
      max-file-size: 5Mb
      enabled: true
      max-request-size: 50Mb

# Mybatis
mybatis:
  # 对应实体类的包结构
  type-aliases-package: nuc.nuc.onlineeducation.exchange.model
  # mapper.xml 文件的路径
  mapper-locations: classpath:/nuc/onlineeducation/exchange/dao/*.xml
  configuration:
    # 启用缓存
    cache-enabled: true
    # 读取超时
    default-statement-timeout: 3000
    # 驼峰命名
    map-underscore-to-camel-case: true
    # 生成返回
    use-generated-keys: true

# PageHelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

